version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile-base
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer
      - ./samples:/samples
      - ./classifier:/classifier
    environment:
      - FLASK_APP=docker.api.api
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=8888"]
#    command: ["gunicorn", "-w 10", "-b 0.0.0.0:8888", "docker.api.api:app"]

  web:
    image:  malgazer_api:latest
#    build:
#      context: ./
#      dockerfile: docker/Dockerfile-base
    depends_on:
      - db
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer
      - ./samples:/samples
    environment:
      - FLASK_APP=docker.web.web
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
#    command: ["gunicorn", "-w 10", "-b 0.0.0.0:8080", "docker.web.web:app"]

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=malgazer