version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile-base
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer
      - ./samples:/samples
      - ./classifier:/classifier
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_API_FLASK_APP}
      - FLASK_ENV=${MALGAZER_API_FLASK_ENV}
    command: ${MALGAZER_API_CMD}

  web:
    image:  malgazer_api:latest
    depends_on:
      - db
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer
      - ./samples:/samples
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_WEB_FLASK_APP}
      - FLASK_ENV=${MALGAZER_WEB_FLASK_ENV}
    command: ${MALGAZER_WEB_CMD}

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    env_file:
      - ./.env
