version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile-base
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer
      - ./samples:/samples
      - ./classifier:/classifier
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_API_FLASK_APP}
      - FLASK_ENV=${MALGAZER_API_FLASK_ENV}
      - MULTIUSER=${MALGAZER_MULTIUSER}
      - COMMAND=${MALGAZER_API_CMD_DEV}

  web:
    image:  malgazer_api:latest
    depends_on:
      - db
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer
      - ./samples:/samples
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_WEB_FLASK_APP}
      - FLASK_ENV=${MALGAZER_WEB_FLASK_ENV}
      - MULTIUSER=${MALGAZER_MULTIUSER}
      - COMMAND=${MALGAZER_WEB_CMD_DEV}
      - SECRET_KEY=${MALGAZER_WEB_SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${MALGAZER_WEB_SECURITY_PASSWORD_SALT}
      - HISTORY_LENGTH=${MALGAZER_WEB_HISTORY_LENGTH}
      - MAIL_USERNAME=${MALGAZER_WEB_MAIL_USERNAME}
      - MAIL_PASSWORD=${MALGAZER_WEB_MAIL_PASSWORD}
      - MAIL_PORT=${MALGAZER_WEB_MAIL_PORT}
      - MAIL_SERVER=${MALGAZER_WEB_MAIL_SERVER}
      - MAIL_USE_SSL=${MALGAZER_WEB_MAIL_USE_SSL}
      - MAIL_USE_TLS=${MALGAZER_WEB_MAIL_USE_TLS}

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    env_file:
      - ./.env
