version: '3'
services:
  classifier:
    build:
      context: ./
      dockerfile: docker/Dockerfile-classifier
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=malgazer