version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile-api
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer
      - ./samples:/samples
      - ./classifier:/classifier

  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer
      - ./samples:/samples

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=malgazer