version: '3'
services:
  classifier:
    build:
      context: ./
      dockerfile: docker/Dockerfile-classifier
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer

  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - classifier
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=malgazer