version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile-base
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/malgazer
      - ./samples:/samples
      - ./classifier:/classifier
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_API_FLASK_APP}
      - FLASK_ENV=${MALGAZER_API_FLASK_ENV}
      - MULTIUSER=${MALGAZER_MULTIUSER}
      - COMMAND=${MALGAZER_API_CMD_DEV}

  web:
    image:  malgazer_api:latest
    depends_on:
      - db
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/malgazer
      - ./samples:/samples
    env_file:
      - ./.env
    environment:
      - FLASK_APP=${MALGAZER_WEB_FLASK_APP}
      - FLASK_ENV=${MALGAZER_WEB_FLASK_ENV}
      - MULTIUSER=${MALGAZER_MULTIUSER}
      - COMMAND=${MALGAZER_WEB_CMD_DEV}
      - SECRET_KEY=${MALGAZER_WEB_SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${MALGAZER_WEB_SECURITY_PASSWORD_SALT}
      - MAIL_USERNAME=registration@malgazer.com
      - MAIL_PASSWORD=PASSWORD
      - MAIL_PORT=465
      - MAIL_SERVER=homie.mail.dreamhost.com
      - MAIL_USE_SSL=1
      - MAIL_USE_TLS=0

  db:
    image: postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    env_file:
      - ./.env
